GET http://localhost:3001/api/books

###

GET http://localhost:3001/api/books/62bc48f961ca75a2a6be6ff6

###

POST http://localhost:3001/api/books
Content-Type: application/json

{
    "title": "1984 etc.",
    "author": "Paulo Coelho",
    "language": "english",
    "likes": 5
}

###

PUT http://localhost:3001/api/books/62bc34830c83ce8baffde2e9
Content-Type: application/json

{
    "title": "The Alchemist",
    "author": "Paulo Coelho",
    "language": "french",
    "likes": 5
}

### 

DELETE  http://localhost:3001/api/books/62bc48fa61ca75a2a6be6ffa

###3